// This file defines the TypeScript interfaces for our main data structures.

// Represents a Note as it is stored in the Appwrite database and returned by our API.
export interface Note {
  $id: string; // Appwrite's unique document ID
  $createdAt: string; // Appwrite's document creation timestamp
  $updatedAt: string; // Appwrite's document update timestamp
  title: string;
  content: string; // This will be a JSON string from the Novel editor
  description?: string; // Optional description
  userId: string;
  createdAt: string; // Our custom creation timestamp
  updatedAt: string; // Our custom update timestamp
}

// Represents the data needed to create a new note.
// We omit the fields that are generated by the server or database.
export type NewNoteData = Omit<
  Note,
  "$id" | "$createdAt" | "$updatedAt" | "userId" | "createdAt" | "updatedAt"
>;

// Represents the data that can be updated on an existing note.
// We can make all fields optional for flexibility.
export type UpdateNoteData = Partial<NewNoteData>;
